### ISSUE TITLE
Connexion des utilisateurs

### ISSUE THREAD

**Issue by enorart** [MargameOff/StumbleSafe#2]
EN TANT QUE Utilisateur de l'application mobile StumbleSafe
JE VEUX Pourvoir me connecter à mon compte
AFIN DE Pouvoir utiliser l'application mobile

Page de connexion (formulaire):
- Email
- Mot de passe

Cas de tests:

Email valide/non connu => affichage d'un message d'erreur de pourquoi et revenir au remplissage du formulaire
Mot de passe invalide => affichage d'un message d'erreur de pourquoi et revenir au remplissage du formulaire
Email et mot de passe valide => utilisateur connecté à l'application

**Comment by Maathis** [comment]
Il faut ajouter un refresh du token valide pour prolonger sa durée lorsqu'on lance l'application

**Comment by Maathis** [comment]
Changer la connexion par email par le nom d'utilisateur
